apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: pokedb
deploy:
  helm:
    releases:
      - name: pokedb
        namespace: pokedb
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        version: 0.1.0
