apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: deck
deploy:
  helm:
    releases:
      - name: deck
        namespace: pokedb
        createNamespace: true
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        version: 0.1.0
