# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pokemon-db
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi
    storageClass: local-path
---
