# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: deck-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi
    storageClass: local-path
